winget.exe install --id Google.Chrome
winget.exe install --id SlackTechnologies.Slack
winget.exe install --id Discord.Discord
winget.exe install --id LINE.LINE
winget.exe install --id Microsoft.VisualStudioCode
winget.exe install --id Git.Git
winget.exe install --id Adobe.AdobeAcrobatReaderDC
winget.exe install --id 7zip.7zip
winget.exe install --id Canonical.Ubuntu
winget.exe install --id dbeaver.dbeaver
winget.exe install --id Mozilla.Thunderbird
winget.exe install --id Microsoft.Office
winget.exe install --id Valve.Steam
winget.exe install --id TeraTermProject.teraterm
winget.exe install --id Balena.Etcher
winget.exe install --id Google.JapaneseIME
winget.exe install --id Nvidia.GeForceExperience
winget.exe install --id Alacritty.Alacritty