name: main

on: [push]

jobs:
  main:
    runs-on: [ubuntu-latest, ubuntu-18.04, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v1
      - name: install dotfiles
        run: bash initial_setting.sh
