name: main

on: [push]

jobs:
  build:
    name: Initial_setting ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v1
      - name: install dotfiles
        run: bash initial_setting.sh
